apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: secret-hummingbird-python 
  janus-idp.io/tekton: secret-hummingbird-python
  backstage.io/kubernetes-id: secret-hummingbird-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: secret-hummingbird-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  