apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: secret-hummingbird-python-gitops-repository
spec:
  url: https://github.com/rhtap-hub/secret-hummingbird-python-gitops